"""
Conference registry — known conferences with metadata.

Update this dict when adding a new conference to the database.
"""

CONFERENCES_2026 = {
    "AEA": {
        "name": "American Economic Association Annual Meeting",
        "website": "https://www.aeaweb.org/conference/2026/program",
        "start_date": "2026-01-03", "end_date": "2026-01-05",
        "location": "San Francisco, USA",
        "scraper_type": "custom", "folder": "aea2026",
    },
    "AFA": {
        "name": "American Finance Association Annual Meeting",
        "website": "https://www.afajof.org/annual-meeting/",
        "start_date": "2026-01-03", "end_date": "2026-01-05",
        "location": "San Francisco, USA",
        "scraper_type": "web", "folder": "afa2026",
    },
    "AFSE": {
        "name": "Association Française de Sciences Economiques (AFSE)",
        "website": "https://afse2026.sciencesconf.org/",
        "start_date": "2026-06-15", "end_date": "2026-06-17",
        "location": "Marseille, France",
        "scraper_type": "sciencesconf", "folder": "afse2026",
    },
    "AFFI": {
        "name": "French Finance Association International Conference",
        "website": "https://affi2026.sciencesconf.org/",
        "start_date": "2026-05-18", "end_date": "2026-05-20",
        "location": "France",
        "scraper_type": "sciencesconf", "folder": "affi2026",
    },
    "BDPCEPR": {
        "name": "Banco de Portugal and CEPR Conference on Financial Intermediation",
        "website": "https://www.bportugal.pt/en/page/conference-financial-intermediation-0",
        "start_date": "2026-06-25", "end_date": "2026-06-26",
        "location": "Lisbon, Portugal",
        "scraper_type": "pdf", "folder": "bdpcepr2026",
    },
    "BFSR": {
        "name": "Bank of Italy, Bocconi, EIEF and CEPR Conference on Financial Stability and Regulation",
        "website": "https://www.bancaditalia.it/chi-siamo/ricerche-convegni/2026-financial-stability/",
        "start_date": "2026-06-11", "end_date": "2026-06-12",
        "location": "Rome, Italy",
        "scraper_type": "pdf", "folder": "bfsr2026",
    },
    "BWBFI": {
        "name": "Bristol Workshop on Banking and Financial Intermediation",
        "website": "https://www.bristol.ac.uk/efm/events/2026/bwbfi/",
        "start_date": "2026-05-07", "end_date": "2026-05-08",
        "location": "Bristol, UK",
        "scraper_type": "web", "folder": "bwbfi2026",
    },
    "CEA": {
        "name": "Canadian Economics Association Annual Conference",
        "website": "https://economics.ca/2026/",
        "start_date": "2026-05-29", "end_date": "2026-05-31",
        "location": "Canada",
        "scraper_type": "web", "folder": "cea2026",
    },
    "CEBRA": {
        "name": "Central Bank Research Association Annual Meeting",
        "website": "https://www.cebra.org/",
        "start_date": "2026-08-27", "end_date": "2026-08-28",
        "location": "Frankfurt, Germany",
        "scraper_type": "web", "folder": "cebra2026",
    },
    "CEPRPS": {
        "name": "CEPR Paris Symposium",
        "website": "https://cepr.org/paris-symposium-2026",
        "start_date": "2026-05-27", "end_date": "2026-05-28",
        "location": "Paris, France",
        "scraper_type": "pdf", "folder": "ceprps2026",
    },
    "CMFR": {
        "name": "Conference on Financial Market Regulation (CFMR)",
        "website": "https://editorialexpress.com/conference/CFMR2026/",
        "start_date": "2026-06-04", "end_date": "2026-06-05",
        "location": "Washington DC, USA",
        "scraper_type": "editorial_express", "folder": "cmfr2026",
    },
    "CMRC": {
        "name": "Community Banking Research Conference",
        "website": "https://www.communitybanking.org/",
        "start_date": "2026-10-01", "end_date": "2026-10-02",
        "location": "USA",
        "scraper_type": "web", "folder": "cmrc2026",
    },
    "CSRA": {
        "name": "Bank of Finland and ESRB Conference on AI and Systemic Risk Analytics",
        "website": "https://www.esrb.europa.eu/",
        "start_date": "2026-10-12", "end_date": "2026-10-13",
        "location": "Helsinki, Finland",
        "scraper_type": "web", "folder": "csra2026",
    },
    "DES": {
        "name": "Danish Economic Society Annual Meeting",
        "website": "https://www.econ.ku.dk/",
        "start_date": "2026-10-29", "end_date": "2026-10-30",
        "location": "Copenhagen, Denmark",
        "scraper_type": "pdf", "folder": "des2026",
    },
    "ECBARC": {
        "name": "ECB Annual Research Conference",
        "website": "https://www.ecb.europa.eu/",
        "start_date": "2025-10-01", "end_date": "2025-10-02",
        "location": "Frankfurt, Germany",
        "scraper_type": "web", "folder": "ecbarc2026",
    },
    "EEA": {
        "name": "European Economic Association Annual Congress",
        "website": "https://www.eea-esem-congresses.org/",
        "start_date": "2026-08-24", "end_date": "2026-08-28",
        "location": "Berlin, Germany",
        "scraper_type": "drupal", "folder": "eea2026",
    },
    "EFA": {
        "name": "European Finance Association Annual Meeting",
        "website": "https://efa2026.org/",
        "start_date": "2026-08-19", "end_date": "2026-08-22",
        "location": "Netherlands",
        "scraper_type": "conftool", "folder": "efa2026",
    },
    "ESSFM": {
        "name": "European Summer Symposium in Financial Markets",
        "website": "https://cepr.org/essfm-2026",
        "start_date": "2026-07-20", "end_date": "2026-07-31",
        "location": "Switzerland",
        "scraper_type": "web", "folder": "essfm2026",
    },
    "GDRE": {
        "name": "Symposium on Money Banking and Finance (GDRE)",
        "website": "https://gdre2026.sciencesconf.org/",
        "start_date": "2026-06-01", "end_date": "2026-06-02",
        "location": "France",
        "scraper_type": "sciencesconf", "folder": "gdre2026",
    },
    "GFA": {
        "name": "German Finance Association Annual Meeting",
        "website": "https://gfa2026.org/",
        "start_date": "2026-09-23", "end_date": "2026-09-25",
        "location": "Germany",
        "scraper_type": "web", "folder": "gfa2026",
    },
    "IAAE": {
        "name": "International Association for Applied Econometrics Annual Conference",
        "website": "https://editorialexpress.com/conference/IAAE2026/",
        "start_date": "2026-06-16", "end_date": "2026-06-19",
        "location": "Belgium",
        "scraper_type": "editorial_express", "folder": "iaae2026",
    },
    "ICMAIF": {
        "name": "International Conference on Macroeconomic Analysis and International Finance",
        "website": "https://icmaif.univ-angers.fr/",
        "start_date": "2026-05-27", "end_date": "2026-05-29",
        "location": "Greece",
        "scraper_type": "pdf", "folder": "icmaif2026",
    },
    "IRMC": {
        "name": "International Risk Management Conference",
        "website": "https://www.irmc2026.org/",
        "start_date": "2026-06-05", "end_date": "2026-06-06",
        "location": "France",
        "scraper_type": "web", "folder": "irmc2026",
    },
    "JMA": {
        "name": "Journées de Microéconomie Appliquée",
        "website": "https://jma2026.sciencesconf.org/",
        "start_date": "2026-06-04", "end_date": "2026-06-05",
        "location": "France",
        "scraper_type": "sciencesconf", "folder": "jma2026",
    },
    "MOFIR": {
        "name": "MoFiR Workshop on Banking",
        "website": "https://mofir.univ-lyon2.fr/",
        "start_date": "2026-06-25", "end_date": "2026-06-26",
        "location": "France",
        "scraper_type": "pdf", "folder": "mofir2026",
    },
    "MPRC": {
        "name": "ECB/IMF Macroprudential Policy and Research Conference",
        "website": "https://www.ecb.europa.eu/",
        "start_date": "2026-10-26", "end_date": "2026-10-27",
        "location": "Frankfurt, Germany",
        "scraper_type": "web", "folder": "mprc2026",
    },
    "MYE": {
        "name": "EAYE Annual Meeting (Spring Meeting of Young Economists)",
        "website": "https://eaye.info/eayeam/",
        "start_date": "2026-05-11", "end_date": "2026-05-13",
        "location": "Bilbao, Spain",
        "scraper_type": "web", "folder": "mye2026",
    },
    "NBER_SI": {
        "name": "NBER Summer Institute",
        "website": "https://www.nber.org/conferences/si2026",
        "start_date": "2026-07-06", "end_date": "2026-07-24",
        "location": "Cambridge, USA",
        "scraper_type": "web", "folder": "nber2026",
    },
    "PDFM": {
        "name": "Paris December Finance Meeting",
        "website": "https://www.parisdecemberfinance.com/",
        "start_date": "2026-12-17", "end_date": "2026-12-18",
        "location": "Paris, France",
        "scraper_type": "web", "folder": "pdfm2026",
    },
    "RCEA": {
        "name": "RCEA International Conference in Economics, Econometrics, and Finance",
        "website": "https://editorialexpress.com/conference/RCEA2026/",
        "start_date": "2026-05-13", "end_date": "2026-05-15",
        "location": "Canada",
        "scraper_type": "editorial_express", "folder": "rcea2026",
    },
    "RES": {
        "name": "Royal Economic Society Annual Conference",
        "website": "https://www.res.org.uk/",
        "start_date": "2026-03-30", "end_date": "2026-04-01",
        "location": "UK",
        "scraper_type": "web", "folder": "res2026",
    },
    "RFILB": {
        "name": "Financial Risks International Forum (RFILB)",
        "website": "https://www.rfilb.org/",
        "start_date": "2026-03-23", "end_date": "2026-03-24",
        "location": "France",
        "scraper_type": "web", "folder": "rfilb2026",
    },
    "SCFICF": {
        "name": "Summer Conference on Financial Intermediation and Corporate Finance",
        "website": "https://scficf.org/",
        "start_date": "2026-06-04", "end_date": "2026-06-05",
        "location": "Portugal",
        "scraper_type": "web", "folder": "scficf",
    },
    "SEA": {
        "name": "Southern Economic Association Annual Meeting",
        "website": "https://www.southerneconomics.org/",
        "start_date": "2026-11-21", "end_date": "2026-11-23",
        "location": "USA",
        "scraper_type": "web", "folder": "sea2026",
    },
    "SFS": {
        "name": "Society for Financial Studies Cavalcade North America",
        "website": "https://sfs-cavalcade.com/",
        "start_date": "2026-05-13", "end_date": "2026-05-15",
        "location": "Canada",
        "scraper_type": "conftool", "folder": "sfs2026",
    },
    "SFWFIR": {
        "name": "BSE Summer Forum Workshop on Financial Intermediation and Risk",
        "website": "https://www.bse.eu/",
        "start_date": "2026-06-18", "end_date": "2026-06-19",
        "location": "Barcelona, Spain",
        "scraper_type": "pdf", "folder": "sfwfir2026",
    },
    "SIC": {
        "name": "NBER Summer Institute (SIC)",
        "website": "https://www.nber.org/conferences/si2026",
        "start_date": "2026-07-13", "end_date": "2026-07-24",
        "location": "Cambridge, USA",
        "scraper_type": "web", "folder": "sic2026",
    },
    "SSFMR": {
        "name": "Swiss Society for Financial Market Research (SGF Conference)",
        "website": "https://www.sgf2026.ch/",
        "start_date": "2026-04-02", "end_date": "2026-04-03",
        "location": "Zurich, Switzerland",
        "scraper_type": "web", "folder": "ssfmr2026",
    },
    "SWCFI": {
        "name": "BIS-CEPR-SFI Conference on Financial Intermediation",
        "website": "https://www.bis.org/",
        "start_date": "2026-06-25", "end_date": "2026-06-26",
        "location": "Switzerland",
        "scraper_type": "web", "folder": "swcfi2026",
    },
    "WCIEA": {
        "name": "World Congress of the International Economic Association",
        "website": "https://www.iea-world.org/",
        "start_date": "2026-06-22", "end_date": "2026-06-26",
        "location": "Colombia",
        "scraper_type": "pdf", "folder": "wciea2026",
    },
    "WEAI": {
        "name": "Western Economics Association International",
        "website": "https://www.weai.org/",
        "start_date": "2026-07-01", "end_date": "2026-07-05",
        "location": "USA",
        "scraper_type": "web", "folder": "weai2026",
    },
    "WFA": {
        "name": "Western Finance Association Annual Meeting",
        "website": "https://www.westernfinance.org/",
        "start_date": "2026-06-24", "end_date": "2026-06-26",
        "location": "USA",
        "scraper_type": "wfa_portal", "folder": "wfa2026",
    },
    "3CMFI": {
        "name": "International Conference on the Climate-Macro-Finance Interface",
        "website": "https://editorialexpress.com/conference/3CMFI/",
        "start_date": "2026-03-23", "end_date": "2026-03-24",
        "location": "Frankfurt, Germany",
        "scraper_type": "editorial_express", "folder": "3cmfi2026",
    },
    "ACMFR": {
        "name": "Annual Conference on Macro-Finance Research",
        "website": "https://editorialexpress.com/conference/ACMFR/",
        "start_date": "2026-05-21", "end_date": "2026-05-22",
        "location": "Greece",
        "scraper_type": "editorial_express", "folder": "ac-mfr",
    },
}
